#! /bin/bash

# Load correct modules
# Load Compilers. For GPU acceleration with openACC, the NVIDIA compilers are required
module load <COMPILERS>
# Maths libraries are required for build (BLAS, LAPACK) as well as an FFT library (FFTW, MKL)
module load <MATHS-LIBRARIES>
module load <FFT-LIBRARY>

# Install location of the castep.mpi binary
INSTALL_LOCATION=<PATH/TO/INSTALL/LOCATION>


echo STARTING COMPILATION

make -j 8 BUILD=fast COMMS_ARCH=mpi # General controls of compilation. BUILD=fast is recommended for production calculations
make -j 8 FFT=<FFT-LIBRARY> MATHLIBS=<MATHS-LIBRARIES> TARGETCPU=portable # Maths and FFT library specification, and of CPU optimisation
make -j 8 GRIMMED3=none GRIMMED4=none # Disabling some unneeded features
make -j 8 INSTALL_DIR=$INSTALL_LOCATION install # Specify install location and perform install procedure

echo COMPILATION COMPLETE
